Add data limits settings to connections
quinn-rs/quinn pull request #1384
Opened 2022-07-15 11:59 UTC by inflation

Although it's seemingly straightforward, I'm not sure `receive_window` is actually used to limit the data. There is a `received_max_data()` but it can only increase `max_data`, and I'm not seeing any reasoning why it can't be set to lower values. Anyone familiar with it are welcome to shed some light.

2022-07-15 20:19 UTC, Ralith requested changes
To be effective, `set_receive_window` must increase `StreamsState::local_max_data` by the difference between the new connection-level receive window and the old one, and set `pending.max_data = true`. If the window shrinks, then instead `local_max_data` must not be changed, but the difference in credit passed to `add_read_credits` in future calls should be silently absorbed.

Adjusting the stream-level receive window is a bit quirky, because the peer will assume the window advertised during the handshake for every new stream until we tell them otherwise, which is particularly significant for peer-initiated streams. This means we can never reduce the size below that level, and so long as the level differs from that we sent in the transport parameters, we must arrange for a `MAX_STREAM_DATA` frame to be sent whenever either side opens a new receive stream. That's all perfectly viable (with a modest bit of extra code), but is it consistent with your requirements?

`max_data` is the limit dictated by the peer and should not be changed.

2022-07-16 01:33 UTC, inflation commented
I would assume the main usage for connection level data limit is to adapt to changing constraints once the connection is established. If these two properties can only go up, maybe we just state it in the doc and don't provide the knobs at all. 

It's still a useful thing to have but would be inconsistent with the options in transport level.

2022-07-16 06:21 UTC, Ralith commented
> If these two properties can only go up

That isn't the case. Existing flow control credit, including flow control credit issued implicitly on new streams, cannot be rescinded, but future flow control credit can be issued according to whatever logic we like, which can include arbitrary decreases.

2022-08-16 23:40 UTC, Ralith commented
https://github.com/quinn-rs/quinn/pull/1386 implemented the connection-scoped configuration; feel free to open a new PR if you still want to pursue dynamic per-stream limits.

2022-08-16 23:40 UTC, closed without merging