Bump quinn-udp version to 0.4
quinn-rs/quinn pull request #1535
Opened 2023-04-14 09:03 UTC by link2xt

It includes a fallback for old Linux and Android systems which do not support setting ECN flag on UDP packets.

2023-04-14 23:12 UTC, Ralith commented
A breaking public dependency version change is a breaking change, so this should be 0.4.

2023-04-19 09:11 UTC, djc commented
@link2xt can you bump this to 0.4.0, please?

2023-04-19 17:31 UTC, Ralith approved these changes

2023-04-19 17:32 UTC, Ralith requested changes
Need to update the version number `quinn` asks for to match.

2023-04-19 17:38 UTC, Ralith approved these changes

2023-04-19 17:50 UTC, merged