Upgrade socket2 to 0.5
quinn-rs/quinn pull request #1558
Opened 2023-05-08 14:57 UTC by djc

This should be okay now that we've bumped our MSRV?

2023-05-09 10:39 UTC, djc commented
The CI failure here is confusing. Tokio's support for `AsFd` was added in https://github.com/quinn-rs/quinn/actions/runs/4924706904/jobs/8798057112?pr=1558 (released in 1.27), and we already have 1.63 as our MSRV.

2023-05-10 05:07 UTC, Ralith requested changes
Great improvements overall!

2023-05-10 05:07 UTC, Ralith commented on .github/workflows/rust.yml
> -          args: --lib --all-features -p quinn-udp -p quinn-proto -p quinn
Stray commit?

2023-05-10 09:11 UTC, djc commented
Bumped the tokio dependency in quinn to 1.28.1 which should make the MSRV test pass.

2023-05-11 02:47 UTC, Ralith approved these changes

2023-05-11 02:47 UTC, merged