Enable packet info and related flags for quinn-udp on Android
quinn-rs/quinn pull request #1758
Opened 2024-02-16 21:47 UTC by conectado

We're using the info obtained with `PKT_INFO`, particularly the destination IP, on multiple platforms including on android.

Most of the socket options used for linux, save for GRO, are available on android, so it's simply adding it to the conditional compilation.

2024-02-16 21:48 UTC, djc approved these changes

2024-02-16 23:20 UTC, Ralith requested changes
Thanks! A few notes:
- Do we need to add android to the case on line 49 too?
- Are GSO/GRO ever available on Android?
- Would love to have CI coverage for this, if you're up for it.

2024-03-10 21:43 UTC, Ralith commented
@conectado do you plan to do any follow-up work here?

2024-03-11 01:09 UTC, thomaseizinger commented
@Ralith Unfortunately, your force-push just broke our CI because we are depending on this commit hash. If you'd like to update the PR, we'd prefer to do it via merge commits only.

2024-03-11 01:11 UTC, thomaseizinger commented
We do plan on following up here but we are preparing the product launch at the moment so there hasn't yet been time for this! :)

2024-03-11 01:11 UTC, thomaseizinger commented
> @Ralith Unfortunately, your force-push just broke our CI because we are depending on this commit hash. If you'd like to update the PR, we'd prefer to do it via merge commits only.

I'll make a dedicated fork for now to un-break CI.

2024-03-11 01:26 UTC, thomaseizinger commented
> * Are GSO/GRO ever available on Android?

We haven't tested this specifically but at least the destination IP is available with this PR.

> * Would love to have CI coverage for this, if you're up for it.

How do you envision to test this in CI? I guess we'd have to use something like QEMU to emulate common Android CPU architectures and then run the tests on it?

2024-03-11 01:36 UTC, Ralith commented
> We haven't tested this specifically but at least the destination IP is available with this PR.

GSO/GRO are unrelated to destination IPs, but are a big CPU efficiency win. They're well-established on Linux so I'd be surprised if they're absent from Android. Not a blocker for this PR, but maybe something you'd want to double-check if you're targeting that platform.

> How do you envision to test this in CI? I guess we'd have to use something like QEMU to emulate common Android CPU architectures and then run the tests on it?

I'm not familiar with Android workflows, so I'm not sure. Some sort of emulator makes sense. Maybe crib from e.g. https://github.com/rustls/rustls-platform-verifier/blob/main/.github/workflows/ci.yml? CI coverage is particularly important here as we're not Android experts ourselves.

2024-03-11 02:45 UTC, Ralith commented
Sure. The only blocking concern is updating the size check on line 49.

2024-03-11 04:14 UTC, thomaseizinger commented
> Sure. The only blocking concern is updating the size check on line 49.

Awesome, thank you! I'll make those changes and open an issue about adding Android CI. Eventually, we want a decent Android CI for the project so once we have to acquire that knowledge, I might be able to port some of it to `quinn`.

2024-03-11 04:32 UTC, thomaseizinger commented
> > Sure. The only blocking concern is updating the size check on line 49.
> 
> Awesome, thank you! I'll make those changes and open an issue about adding Android CI. Eventually, we want a decent Android CI for the project so once we have to acquire that knowledge, I might be able to port some of it to `quinn`.

I opened an issue and [linked](https://users.rust-lang.org/t/twir-call-for-participation/4821/621?u=thomaseizinger) it on the rust-lang forum to be included in next week's TWIR. Maybe somebody volunteers :)

I'll nudge @conectado to push a fix for the size check!

2024-03-11 19:50 UTC, Ralith approved these changes
Thanks!

2024-03-11 19:50 UTC, conectado commented
@thomaseizinger thanks for taking over! :)

@ralith Pushed the fix.

Also, it will probably just work enabling GRO/GSO in android since the socket options [exists in the kernel](https://cs.android.com/android/platform/superproject/main/+/main:prebuilts/runtime/mainline/runtime/sdk/android/arm/include/bionic/libc/kernel/uapi/linux/udp.h;l=20-21?q=udp_segment&ss=android%2Fplatform%2Fsuperproject%2Fmain) I can try it on a follow up PR when I have a bit more availability.

2024-03-11 19:55 UTC, merged