Expose RecvStream::poll_read & poll_read_chunk
quinn-rs/quinn pull request #1784
Opened 2024-03-17 02:45 UTC by jean-airoldie

Closes #1782

2024-03-17 02:49 UTC, jean-airoldie commented
Now for this one, the `poll_read_chunk` is not part of `AsyncRead`, so technically this would force you to support that new method, but I figured that if it might result in improved read performance, that might be desirable to expose too.

2024-03-17 02:51 UTC, jean-airoldie commented
In my use case, I'm thinking of using `poll_read` to read the size prefix, followed by `poll_read_chunk` to read the actual message, for instance.

2024-03-17 03:47 UTC, Ralith requested changes
> I figured that if it might result in improved read performance, that might be desirable to expose too.

This is speculative. I'd prefer to avoid further complicating our API without a concrete use case that benefits, particularly as using `poll_read_buf` correctly is itself complex. For example, your use case would need to handle consuming any number of chunks before reaching the desired total length, and you'd then have to either deal with having non-contiguous data in whatever downstream processing you do, or copy everything into a single buffer, at best duplicating the logic already provided by `poll_read`.

2024-03-17 03:47 UTC, Ralith commented on quinn/src/recv_stream.rs
> +    /// Attempts to read a chunk from the stream into buf.
There is no `buf` in this context.

2024-03-17 04:34 UTC, jean-airoldie commented
> This is speculative. I'd prefer to avoid further complicating our API without a concrete use case that benefits, particularly as using poll_read_buf correctly is itself complex.

Fair enough. In my understanding, the potential benefit was from the unordered read, even if you have to copy the chunks into a separate buffer.

2024-03-17 17:45 UTC, Ralith approved these changes

2024-03-18 11:24 UTC, djc approved these changes

2024-03-18 11:26 UTC, djc commented
(Needs a rebase. Would be nice if you can squash the commits here.)

2024-03-19 08:10 UTC, djc approved these changes

2024-03-19 08:10 UTC, merged