Allows build on Solaris (#1877)
quinn-rs/quinn pull request #1916
Opened 2024-07-08 13:49 UTC by psumbera

This allows build on Solaris. Unfortunately at this moment tests are failing like this:
```
     Running unittests src/lib.rs (target/debug/deps/quinn-94a8797a83ab1c78)

running 18 tests
test work_limiter::tests::limit_work ... ok
test tests::local_addr ... ok
test tests::close_endpoint ... ok
test tests::handshake_timeout ... ok
test tests::zero_rtt ... FAILED
test tests::export_keying_material ... FAILED
test tests::rebind_recv ... FAILED
test tests::stress_stream_receive_window ... FAILED
test tests::echo_v4 ... FAILED
test tests::stress_both_windows ... FAILED
test tests::read_after_close ... FAILED
test tests::echo_v6 ... FAILED
test tests::stress_receive_window ... FAILED
test tests::echo_dualstack ... FAILED
test tests::ip_blocking ... FAILED
test tests::multiple_conns_with_zero_length_cids ... FAILED
test tests::stream_id_flow_control has been running for over 60 seconds
test tests::two_datagram_readers has been running for over 60 seconds
^C
```

2024-07-08 13:53 UTC, psumbera commented
(Note that there might be some problems with `tokio` and/or `mio` as `mio` on Solaris is using `poll()` interface).

2024-07-08 14:53 UTC, djc commented
Can you add a separate commit that bumps the MSRV?

2024-07-08 15:34 UTC, djc approved these changes

2024-07-08 15:34 UTC, djc commented
Thanks!

2024-07-09 02:26 UTC, Ralith requested changes
Thanks! What happened to the FFI definitions drafted in libc that were thought to be necessary?

> Unfortunately at this moment tests are failing like this

That's unfortunate. Is there an upstream issue open for the behavior in tokio that you suspect is responsible?

Regardless, the most important question is whether the quinn-udp tests pass. Do they?

2024-07-09 02:26 UTC, Ralith commented on quinn-udp/src/unix.rs
> -        #[cfg(any(target_os = "freebsd", target_os = "macos", target_os = "ios"))]
Unintended change?

2024-07-11 12:44 UTC, psumbera commented
> Thanks! What happened to the FFI definitions drafted in libc that were thought to be necessary?

I'm keeping `libc` changes separately in my ws:

```
--- a/quinn-udp/Cargo.toml
+++ b/quinn-udp/Cargo.toml
@@ -19,8 +19,8 @@ default = ["log"]
 log = ["tracing/log"]

 [dependencies]
-libc = "0.2.113"
-socket2 = { workspace = true }
+libc = { git = "https://github.com/psumbera/libc.git", branch = "quinn4" }
+socket2 = { git = "https://github.com/psumbera/socket2.git", branch = "quinn" }
 tracing = { workspace = true }

 [target.'cfg(windows)'.dependencies]
```

Note that use of modified `socket2` is also because of `libc`.

This is because I had to include to `libc` changes the use of `__xnet_*` socket functions:
https://github.com/rust-lang/libc/pull/3717/commits/828115747c1cd982b190060badaebf7ff284d27a
and this required me to rebuild whole `Rust` and `socket2` had to use this modified `libc` as well. 

> > Unfortunately at this moment tests are failing like this
> 
> That's unfortunate. Is there an upstream issue open for the behavior in tokio or mio that you suspect is responsible?

With use of `__xnet_*` functions in libc it's better now:

```
running 18 tests
test work_limiter::tests::limit_work ... ok
test tests::local_addr ... ok
test tests::close_endpoint ... ok
test tests::echo_v6 ... FAILED
test tests::ip_blocking ... ok
test tests::two_datagram_readers ... ok
test tests::export_keying_material ... ok
test tests::rebind_recv ... ok
test tests::multiple_conns_with_zero_length_cids ... ok
test tests::stream_id_flow_control ... ok
test tests::read_after_close ... ok
test tests::echo_v4 ... ok
test tests::zero_rtt ... ok
test tests::handshake_timeout ... ok                                                                                              test tests::echo_dualstack ... ok                                                                                                 test tests::stress_both_windows has been running for over 60 seconds                                                              test tests::stress_receive_window has been running for over 60 seconds                                                            test tests::stress_stream_receive_window has been running for over 60 seconds                                                     ^C                                               
```
 
> Regardless, the most important question is whether the quinn-udp tests pass. Do they?

I had to disable some tests the same way NetBSD and OpenBSD do and it now passes like this:

```
running 3 tests
test gso ... ignored
test basic ... ok
test ecn_v6 ... ok
```

2024-07-11 17:44 UTC, Ralith commented
> I'm keeping libc changes separately in my ws:

If the definitions introduced/altered in the libc PR are necessary for the quinn-udp changes to work, then please vendor them in this PR, as mentioned in https://github.com/quinn-rs/quinn/issues/1877#issuecomment-2209389879. Once the libc change is merged and released, we can drop the vendored definitions.

2024-08-20 09:26 UTC, djc approved these changes
Thanks! Do you know of any good ways to test Solaris in CI?

2024-08-20 09:27 UTC, psumbera commented
Now with libc 0.2.158 everything should be ok.

2024-08-20 09:33 UTC, psumbera commented
> Thanks! Do you know of any good ways to test Solaris in CI?

Unfortunately no. There is Solaris CBE release which could be used (https://blogs.oracle.com/solaris/post/announcing-the-first-oracle-solaris-114-cbe). But I don't know how this could be used for CI...

2024-08-20 09:37 UTC, djc commented
The vmactions org (whose Action we use for FreeBSD) appears to also have a Solaris action:

https://github.com/vmactions/solaris-vm

2024-08-20 12:51 UTC, mxinden commented
For what it is worth, here is the equivalent FreeBSD workflow mentioned above:

https://github.com/quinn-rs/quinn/blob/b9ce9c8c94e9dbdfdd4e1e4f02196da992d1fd97/.github/workflows/rust.yml#L12-L33

2024-08-20 18:26 UTC, Ralith approved these changes
Thanks! CI coverage would be a great follow-up.

2024-08-20 18:33 UTC, merged