Revert "Implement fallback for `sendmmsg` and `recvmmsg`"
quinn-rs/quinn pull request #1966
Opened 2024-08-14 12:23 UTC by mxinden

This reverts commit e6f184489e703bcf70850f99373c88746c250662.

e6f18448 called `sendmmsg` and `recvmmsg` through `libc::syscall` instead of `libc::sendmmsg` and `libc::recvmmsg`, thus preventing linking issues on old Android systems where `libc::sendmmsg` and `libc::recvmmsg` isn't available.

In https://github.com/quinn-rs/quinn/issues/1503#issuecomment-2285962727 the suggestion was made to no longer support these old Android systems (API level 16).

This commit reverts e6f18448. Given that `sendmmsg` support was previously dropped in ee088265, only the `recvmmsg` calls are reverted.

---

I suggest merging https://github.com/quinn-rs/quinn/pull/1950 first, thus properly covering this change on CI.

Alternative to https://github.com/quinn-rs/quinn/pull/1964. Given the additional simplicity, my preference is for this change.

2024-08-14 13:25 UTC, mxinden commented on quinn-udp/src/unix.rs
> +    let ret = libc::recvmmsg(sockfd, msgvec, vlen as _, flags, timeout) as libc::c_int;
Note the `as _` here. The alternative would be:

``` diff
modified   quinn-udp/src/unix.rs
@@ -442,7 +442,11 @@ unsafe fn recvmmsg_with_fallback(
     let flags = 0;
     let timeout = ptr::null_mut::<libc::timespec>();
 
-    let ret = libc::recvmmsg(sockfd, msgvec, vlen as _, flags, timeout) as libc::c_int;
+    let ret = {
+        #[cfg(target_os = "freebsd")]
+        let vlen = vlen as usize;
+        libc::recvmmsg(sockfd, msgvec, vlen, flags, timeout) as libc::c_int
+    };
     if ret != -1 {
         return ret;
     }
```

The additional scope is need in order to preserve the original `vlen` type (`c_int`) (i.e. not shadow `vlen`) for the `recvmmsg_fallback` below.

2024-08-14 13:55 UTC, mxinden commented on quinn-udp/src/unix.rs
> +    let ret = libc::recvmmsg(sockfd, msgvec, vlen as _, flags, timeout) as libc::c_int;
Or we don't pass `vlen` to `recvmmsg_fallback` at all:

``` diff
modified   quinn-udp/src/unix.rs
@@ -181,6 +181,10 @@ impl UdpSocketState {
         bufs: &mut [IoSliceMut<'_>],
         meta: &mut [RecvMeta],
     ) -> io::Result<usize> {
+        if bufs.len() == 0 {
+            return Ok(0);
+        }
+
         recv(socket.0, bufs, meta)
     }
 
@@ -442,7 +446,9 @@ unsafe fn recvmmsg_with_fallback(
     let flags = 0;
     let timeout = ptr::null_mut::<libc::timespec>();
 
-    let ret = libc::recvmmsg(sockfd, msgvec, vlen as _, flags, timeout) as libc::c_int;
+    #[cfg(target_os = "freebsd")]
+    let vlen = vlen as usize;
+    let ret = libc::recvmmsg(sockfd, msgvec, vlen, flags, timeout) as libc::c_int;
     if ret != -1 {
         return ret;
     }
@@ -451,7 +457,7 @@ unsafe fn recvmmsg_with_fallback(
     match e.raw_os_error() {
         Some(libc::ENOSYS) => {
             // Fallback to `recvmsg`.
-            recvmmsg_fallback(sockfd, msgvec, vlen)
+            recvmmsg_fallback(sockfd, msgvec)
         }
         _ => -1,
     }
@@ -461,15 +467,8 @@ unsafe fn recvmmsg_with_fallback(
 /// for systems which do not support `recvmmsg`
 /// such as Linux <2.6.33.
 #[cfg(not(any(target_os = "macos", target_os = "ios", target_os = "openbsd")))]
-unsafe fn recvmmsg_fallback(
-    sockfd: libc::c_int,
-    msgvec: *mut libc::mmsghdr,
-    vlen: libc::c_uint,
-) -> libc::c_int {
+unsafe fn recvmmsg_fallback(sockfd: libc::c_int, msgvec: *mut libc::mmsghdr) -> libc::c_int {
     let flags = 0;
-    if vlen == 0 {
-        return 0;
-    }
 
     let n = libc::recvmsg(sockfd, &mut (*msgvec).msg_hdr, flags);
     if n == -1 {
```

Your call. I am fine either way.

2024-08-21 06:30 UTC, mxinden commented
@djc @Ralith do you have some time to give this pull request a review?

2024-08-21 08:51 UTC, djc approved these changes
This makes sense to me, but I'll want to wait for @Ralith's opinion.

2024-08-27 07:15 UTC, mxinden commented
Friendly ping @Ralith. Do you have some time to take a look?

2024-09-01 02:54 UTC, Ralith requested changes
Do we still need the `ENOSYS` path and the `recvmmsg_fallback` definition? Prior to e6f184489e703bcf70850f99373c88746c250662 we just called `libc::recvmmgs` directly rather than wrapping it at all -- can we return to that?

2024-09-02 10:17 UTC, mxinden commented
Thank you for the review!

I am fine with no longer supporting both:

1. Android API Level 16 (i.e. Android 4)
2. Linux Kernel < 2.6.33

(1) allows us to drop indirection `libc::syscall(libc::SYS_sendmmsg` in favor of a direct call to `libc::recvmmsg`. (2) allows us to drop `recvmsg` (one `m`) fallback.

I updated this pull request accordingly.

@Ralith would you mind taking another look?

2024-09-02 16:13 UTC, Ralith approved these changes
LGTM! I don't think Rust officially supports targeting linux 2.x anyway.

2024-09-03 09:05 UTC, merged

2024-09-03 09:23 UTC, djc commented
* Published quinn-udp v0.5.5 at registry `crates-io`
* [new tag]           quinn-udp-0.5.5 -> quinn-udp-0.5.5
* [Release notes](https://github.com/quinn-rs/quinn/releases/tag/quinn-udp-0.5.5)