Expose cid genearator customization API in endpoint builder
quinn-rs/quinn pull request #925
Opened 2020-11-24 20:34 UTC by liwenjieQu

A CID generator interface was implemented in transport layer https://github.com/quinn-rs/quinn/pull/851 but there is still no way to actually enable this feature when HTTP/3 endpoint is built. This PR provides an API in `EndpointBuilder` to allow customization on CID generator.

2020-11-24 22:38 UTC, Ralith approved these changes
Good catch, thanks!

2020-11-24 22:38 UTC, Ralith commented on quinn/src/builders.rs
> +    pub fn use_customized_cid<F: Fn() -> Box<dyn ConnectionIdGenerator> + Send + Sync + 'static>(
```suggestion
    pub fn connection_id_generator<F: Fn() -> Box<dyn ConnectionIdGenerator> + Send + Sync + 'static>(
```
For builder methods, preferred naming is a noun specifying the property being modified.

2020-11-24 22:39 UTC, Ralith requested changes

2020-11-24 22:39 UTC, Ralith commented on quinn/src/builders.rs
> +    pub fn use_customized_cid<F: Fn() -> Box<dyn ConnectionIdGenerator> + Send + Sync + 'static>(
(fixing review status)

2020-11-25 01:13 UTC, Ralith approved these changes
Thanks!

2020-11-25 01:35 UTC, liwenjieQu commented
Thanks Benjamin!

2020-11-25 08:13 UTC, merged

2020-11-25 08:13 UTC, djc commented
Nice, thanks for adding this!